name: Build Official Site
on:
  push:
    branchs:
      - 'master'

jobs:
  build:
    name: Build Server Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codespace
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: sheason/www
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm i
          npm run build
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      